#!/bin/sh

. base.sh

find public \
	-type f \
	-not -name 'README.md' \
	-not -name '.git' \
	-delete
hugo
cd public || die
git status
git add .
git commit -m "Publish site $(date +"%Y-%m-%d %H:%M:%S")"
git push origin master
